[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
via_ir = true
auto_detect_solc = true

remappings = [
  "account-abstraction/=lib/account-abstraction/",
  "@account-abstraction/=lib/account-abstraction/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

fs_permissions = [
  { access = "read-write", path = "./results" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
